### PR TITLE
Update error message for nested match, fix style and comments

### LINKED ISSUE #88: Reword violation message for nested matches >= 3 layers deep
Right now, if a student has a nested match 3 layers deep, they get the following message:
```
using nested match statements more than three layers deep
```

This should be changed to say "three or more layers deep".

Code in question: https://github.com/upenn-cis1xx/camelot/blob/master/lib/style/verbose.ml#L58-L85

### PR DESCRIPTION
**Pull request by jxiao**
Closes #88

### CODE REVIEW

**Review by KeenWill — APPROVED** [review]

File: test/examples/verbose.ml [hunk 1]
```diff
@@ -25,6 +25,18 @@ let f () = if x then
...
+  let l = [] in
+  begin match l with
+    | [] ->
+      begin match l with
+        | [] -> true
+        | _ -> false
+      end
+    | _ -> true
+  end
+
```
Comment (jxiao) [inline test/examples/verbose.ml:39]: Added this test case here, which ended up adjusting the line numbers of the violations in `test/test.ml`.

**Review by KeenWill — APPROVED** [review]
lgtm!
